Dataset: BPIC12
Aggregate Type: AggregateType.AVG
Traceback (most recent call last):
  File "/gpfs/hpc/home/elkoumy/amun/run_experiment_slurm.py", line 149, in <module>
    run_experiment(data,parameter)
  File "/gpfs/hpc/home/elkoumy/amun/run_experiment_slurm.py", line 53, in run_experiment
    dfg_freq, dfg_time = read_xes(data_dir,dataset, aggregate_type)
  File "/gpfs/hpc/home/elkoumy/amun/amun/input_module.py", line 24, in read_xes
    dfg_time =get_dfg_time(data,aggregate_type)
  File "/gpfs/hpc/home/elkoumy/amun/amun/input_module.py", line 53, in get_dfg_time
    temp_row= data.iloc[0]
  File "/gpfs/hpc/home/elkoumy/.conda/envs/amun-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/gpfs/hpc/home/elkoumy/.conda/envs/amun-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 2102, in _getitem_axis
    self._validate_integer(key, axis)
  File "/gpfs/hpc/home/elkoumy/.conda/envs/amun-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 2009, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
